# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {
  "hi": "96%",
  "hu": "31%",
  "it": "56%",
  "tr": "93%",
  "ua": "85%"
}