# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {
  "ar": "0%",
  "bn": "20%",
  "cs": "98%",
  "de": "97%",
  "es": "0%",
  "hi": "92%",
  "hr": "0%",
  "hu": "97%",
  "it": "97%",
  "ja": "97%",
  "pl": "42%",
  "ru": "92%",
  "sr": "23%",
  "tr": "97%",
  "ua": "92%",
  "zh_TW": "97%"
}