# Autogenerated file, do not modify it!!!

untranslatedPercentage = {
  "ar": "87%",
  "bg": "90%",
  "bn": "45%",
  "cs": "94%",
  "da": "29%",
  "el": "72%",
  "fa": "71%",
  "fi": "0%",
  "he": "72%",
  "hi": "81%",
  "hr": "86%",
  "id": "88%",
  "ja": "93%",
  "mk": "95%",
  "nb": "85%",
  "nn-NO": "8%",
  "pt_BR": "96%",
  "pt_PT": "96%",
  "ru": "89%",
  "si": "9%",
  "sl": "88%",
  "sv": "0%",
  "tg": "21%",
  "tr": "85%",
  "ua": "84%",
  "vi": "99%"
}

languageCredits = {
  "ar": [
    {
      "name": "Abdu11ahAS",
      "link": "https://github.com/Abdu11ahAS"
    },
    {
      "name": "FancyCookin",
      "link": "https://github.com/FancyCookin"
    },
    {
      "name": "mo9a7i",
      "link": "https://github.com/mo9a7i"
    }
  ],
  "bg": [
    {
      "name": "Vasil Kolev",
      "link": ""
    }
  ],
  "bn": [
    {
      "name": "fluentmoheshwar",
      "link": "https://github.com/fluentmoheshwar"
    },
    {
      "name": "Mushfiq Iqbal Rayon",
      "link": ""
    },
    {
      "name": "Nilavra Bhattacharya",
      "link": ""
    }
  ],
  "ca": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "cs": [
    {
      "name": "panther7",
      "link": "https://github.com/panther7"
    }
  ],
  "da": [
    {
      "name": "mikkolukas",
      "link": "https://github.com/mikkolukas"
    },
    {
      "name": "yrjarv",
      "link": "https://github.com/yrjarv"
    }
  ],
  "de": [
    {
      "name": "CanePlayz",
      "link": "https://github.com/CanePlayz"
    },
    {
      "name": "Datacra5H",
      "link": "https://github.com/Datacra5H"
    },
    {
      "name": "ebnater",
      "link": "https://github.com/ebnater"
    },
    {
      "name": "michaelmairegger",
      "link": "https://github.com/michaelmairegger"
    },
    {
      "name": "Seeloewen",
      "link": "https://github.com/Seeloewen"
    }
  ],
  "el": [
    {
      "name": "antwnhsx  @wobblerrrgg",
      "link": "https://github.com/antwnhsx  @wobblerrrgg"
    }
  ],
  "en": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    },
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "es": [
    {
      "name": "apazga",
      "link": "https://github.com/apazga"
    },
    {
      "name": "dalbitresb12",
      "link": "https://github.com/dalbitresb12"
    },
    {
      "name": "evaneliasyoung",
      "link": "https://github.com/evaneliasyoung"
    },
    {
      "name": "guplem",
      "link": "https://github.com/guplem"
    },
    {
      "name": "JMoreno97",
      "link": "https://github.com/JMoreno97"
    },
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    },
    {
      "name": "rubnium",
      "link": "https://github.com/rubnium"
    },
    {
      "name": "uKER",
      "link": "https://github.com/uKER"
    }
  ],
  "fa": [
    {
      "name": "itsarian",
      "link": "https://github.com/itsarian"
    },
    {
      "name": "Mahdi-Hazrati",
      "link": "https://github.com/Mahdi-Hazrati"
    },
    {
      "name": "smsi2001",
      "link": "https://github.com/smsi2001"
    }
  ],
  "fi": [],
  "fr": [
    {
      "name": "Evans Costa",
      "link": ""
    },
    {
      "name": "Rémi Guerrero",
      "link": ""
    },
    {
      "name": "W1L7dev",
      "link": "https://github.com/W1L7dev"
    }
  ],
  "he": [
    {
      "name": "Oryan",
      "link": ""
    }
  ],
  "hi": [
    {
      "name": "atharva_xoxo",
      "link": "https://github.com/atharva_xoxo"
    },
    {
      "name": "satanarious",
      "link": "https://github.com/satanarious"
    }
  ],
  "hr": [
    {
      "name": "Stjepan Treger",
      "link": ""
    }
  ],
  "hu": [
    {
      "name": "gidano",
      "link": "https://github.com/gidano"
    }
  ],
  "id": [
    {
      "name": "arthackrc",
      "link": "https://github.com/arthackrc"
    },
    {
      "name": "joenior",
      "link": "https://github.com/joenior"
    }
  ],
  "it": [
    {
      "name": "David Senoner",
      "link": ""
    },
    {
      "name": "giacobot",
      "link": "https://github.com/giacobot"
    },
    {
      "name": "maicol07",
      "link": "https://github.com/maicol07"
    },
    {
      "name": "mapi68",
      "link": "https://github.com/mapi68"
    },
    {
      "name": "mrfranza",
      "link": "https://github.com/mrfranza"
    },
    {
      "name": "Rosario Di Mauro",
      "link": ""
    }
  ],
  "ja": [
    {
      "name": "nob-swik",
      "link": "https://github.com/nob-swik"
    },
    {
      "name": "sho9029",
      "link": ""
    },
    {
      "name": "Takaki IEKURA",
      "link": ""
    },
    {
      "name": "Yuki Takase",
      "link": ""
    }
  ],
  "ko": [
    {
      "name": "minbert",
      "link": "https://github.com/minbert"
    },
    {
      "name": "shblue21",
      "link": "https://github.com/shblue21"
    }
  ],
  "mk": [
    {
      "name": "LordDeatHunter",
      "link": ""
    }
  ],
  "nb": [
    {
      "name": "jonaskm",
      "link": "https://github.com/jonaskm"
    },
    {
      "name": "yrjarv",
      "link": "https://github.com/yrjarv"
    }
  ],
  "nl": [
    {
      "name": "abbydiode",
      "link": "https://github.com/abbydiode"
    },
    {
      "name": "Stephan-P",
      "link": "https://github.com/Stephan-P"
    }
  ],
  "nn-NO": [],
  "pl": [
    {
      "name": "KamilZielinski",
      "link": "https://github.com/KamilZielinski"
    },
    {
      "name": "kwiateusz",
      "link": "https://github.com/kwiateusz"
    },
    {
      "name": "RegularGvy13",
      "link": "https://github.com/RegularGvy13"
    }
  ],
  "pt_BR": [
    {
      "name": "maisondasilva",
      "link": "https://github.com/maisondasilva"
    },
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    },
    {
      "name": "wanderleihuttel",
      "link": "https://github.com/wanderleihuttel"
    }
  ],
  "pt_PT": [
    {
      "name": "PoetaGA",
      "link": "https://github.com/PoetaGA"
    },
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "ro": [
    {
      "name": "Mihai Vasiliu",
      "link": ""
    },
    {
      "name": "TZACANEL",
      "link": ""
    }
  ],
  "ru": [
    {
      "name": "bropines",
      "link": "https://github.com/bropines"
    },
    {
      "name": "flatron4eg",
      "link": "https://github.com/flatron4eg"
    },
    {
      "name": "katrovsky",
      "link": "https://github.com/katrovsky"
    },
    {
      "name": "Sergey",
      "link": ""
    },
    {
      "name": "sklart",
      "link": "https://github.com/sklart"
    }
  ],
  "si": [
    {
      "name": "SashikaSandeepa",
      "link": "https://github.com/SashikaSandeepa"
    }
  ],
  "sl": [
    {
      "name": "rumplin",
      "link": "https://github.com/rumplin"
    }
  ],
  "sr": [
    {
      "name": "daVinci13",
      "link": "https://github.com/daVinci13"
    },
    {
      "name": "Nemanja Djurcic",
      "link": ""
    }
  ],
  "sv": [],
  "tg": [
    {
      "name": "lasersPew",
      "link": ""
    }
  ],
  "th": [
    {
      "name": "apaeisara",
      "link": "https://github.com/apaeisara"
    },
    {
      "name": "dulapahv",
      "link": "https://github.com/dulapahv"
    }
  ],
  "tr": [
    {
      "name": "ahmetozmtn",
      "link": "https://github.com/ahmetozmtn"
    },
    {
      "name": "gokberkgs",
      "link": "https://github.com/gokberkgs"
    }
  ],
  "ua": [
    {
      "name": "Artem Moldovanenko",
      "link": ""
    },
    {
      "name": "Operator404",
      "link": ""
    }
  ],
  "vi": [
    {
      "name": "legendsjoon",
      "link": "https://github.com/legendsjoon"
    },
    {
      "name": "txavlog",
      "link": "https://github.com/txavlog"
    }
  ],
  "zh_CN": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "adfnekc",
      "link": "https://github.com/adfnekc"
    },
    {
      "name": "BUGP Association",
      "link": ""
    },
    {
      "name": "ciaran",
      "link": ""
    },
    {
      "name": "CnYeSheng",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    }
  ],
  "zh_TW": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "CnYeSheng",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    },
    {
      "name": "yrctw",
      "link": "https://github.com/yrctw"
    }
  ]
}