name: 'Issues with the WingetUI program'
description: Report issues and unexpected behaviour from the WingetUI interface or its components, not from the package managers
title: "[BUG] (Enter your description here)"
labels: ["bug"]
assignees: marticliment
body:
  - type: checkboxes
    attributes:
      label: Please confirm these before moving forward
      description: Please confirm the following before posting your issue.
      options:
        - label: I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
          required: true
        - label: I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
          required: true
        - label: I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
          required: true
  - type: textarea
    attributes:
      label: Describe your issue
      placeholder: Explain the issue you are experiencing, providing as much details as possible about it
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      placeholder: How can this issue be reproduced? List here, if known, the steps followed before this issue appeared
    validations:
      required: false
  - type: textarea
    attributes:
      label: WingetUI Log
      render: "text"
      placeholder: Paste here your WingetUI logs. Click the button on the top-right corner of WingetUI -> WingetUI Log
    validations:
      required: true
  - type: textarea
    attributes:
      label: Package Managers Logs
      render: "text"
      placeholder: Paste here your Package Manager logs. Click the button on the top-right corner of WingetUI -> Package manager logs
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant information
      placeholder: Other relevant information about this issue. Perhaps if you have some special settings enabled, or any other detail that could be related.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots and videos
      placeholder: If applicable, please post here a video or a screenshot of the issue.
    validations:
      required: false
