name: '📚 Report a documentation issue'
description: Report issues or suggestions related to the documentation.
title: "[DOCUMENTATION] (Enter your description here)"
labels: ["documentation"]
assignees: marticliment
body:
  - type: checkboxes
    attributes:
      label: Please confirm these before moving forward
      description: Please confirm the following before posting your issue.
      options:
        - label: I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
          required: true
        - label: I have checked the existing documentation for solutions.
          required: true
  - type: input
    attributes:
      label: Documentation Version
      placeholder: 'e.g., 1.0.0'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your issue or suggestion
      placeholder: Explain the issue or suggestion you have, providing as many details as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment details
      placeholder: Provide details about your environment, such as operating system, browser, and version.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: Provide steps to reproduce the issue, if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      placeholder: Provide any additional information that may help in resolving the issue or implementing the suggestion.
    validations:
      required: false
