name: '🚧 Suggest an improvement for an existing feature'
description: Propose an improvement to UniGetUI.
title: "[IMPROVEMENT] (Enter your description here)"
labels: ["enhancement"]
assignees: marticliment
body:
  - type: checkboxes
    attributes:
      label: Please confirm these before moving forward.
      description: Please confirm the following before posting your issue.
      options:
        - label: I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
          required: true
        - label: This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
          required: true
        - label: This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).
          required: true
  - type: textarea
    attributes:
      label: Describe the improvement
      placeholder: Explain how you see this enhancement, providing as many details as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe how this improvement could help users
      placeholder: For what would it be useful?
    validations:
      required: true
