name: '💡 Propose a new feature'
description: Propose a new feature that could be useful in UniGetUI.
title: "[FEATURE REQUEST] (Enter your description here)"
labels: ["new-feature"]
assignees: marticliment
body:
  - type: checkboxes
    attributes:
      label: Please confirm these before moving forward.
      description: Please confirm the following before posting your issue.
      options:
        - label: I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
          required: true
        - label: This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).
          required: true
  - type: textarea
    attributes:
      label: Describe the new feature
      placeholder: Explain how you see this new feature, providing as many details as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe how this new feature could help users
      placeholder: For what would it be useful?
    validations:
      required: true
