name: '🚑 Report a crash or a hang'
description: UniGetUI is not launching, is hard-crashing, or is hanging at some point.
title: "[CRASH] (Enter your description here)"
labels: ["bug", "important"]
assignees: marticliment
body:
  - type: checkboxes
    attributes:
      label: Please confirm these before moving forward.
      description: Please confirm the following before posting your issue.
      options:
        - label: I have tried deleting a folder named `.wingetui` placed on the user directory.
          required: true
        - label: I have tried reinstalling WingetUI.
          required: true
        - label: I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
          required: true
  - type: textarea
    attributes:
      label: Describe your crash
      placeholder: What were you doing when this happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs (if possible)
      placeholder: If you get an error report or a message, please post it here.
      render: "text"
    validations:
      required: false
  - type: textarea
    attributes:
      label: More details
      placeholder: Do you have any other valuable information about this issue?
    validations:
      required: false
