OC_OPERATION_SUCCEEDED = 0
OC_NO_APPLICABLE_UPDATE_FOUND = 92849
OC_NEEDS_RESTART = 3

LIST_OC_OPERATION_SUCCEEDED = (OC_OPERATION_SUCCEEDED, OC_NO_APPLICABLE_UPDATE_FOUND, OC_NEEDS_RESTART)

OC_INCORRECT_HASH = 2
OC_NEEDS_ELEVATION = 1603
OC_NEEDS_SCOOP_ELEVATION = 1602