# Autogenerated file, do not modify it!!!

contributors = [
  "marticliment",
  "ppvnf",
  "panther7",
  "RavenMacDaddy",
  "MisterEvans78",
  "sklart",
  "vedantmgoyal2009",
  "neoOpus",
  "Satanarious",
  "candrapersada",
  "harleylara",
  "sitiom",
  "victorelec14"
]

contributorsInfo = [
  {
    "name": "marticliment",
    "link": "https://github.com/marticliment",
    "contributions": 747
  },
  {
    "name": "ppvnf",
    "link": "https://github.com/ppvnf",
    "contributions": 59
  },
  {
    "name": "panther7",
    "link": "https://github.com/panther7",
    "contributions": 24
  },
  {
    "name": "RavenMacDaddy",
    "link": "https://github.com/RavenMacDaddy",
    "contributions": 21
  },
  {
    "name": "MisterEvans78",
    "link": "https://github.com/MisterEvans78",
    "contributions": 3
  },
  {
    "name": "sklart",
    "link": "https://github.com/sklart",
    "contributions": 3
  },
  {
    "name": "vedantmgoyal2009",
    "link": "https://github.com/vedantmgoyal2009",
    "contributions": 2
  },
  {
    "name": "neoOpus",
    "link": "https://github.com/neoOpus",
    "contributions": 1
  },
  {
    "name": "Satanarious",
    "link": "https://github.com/Satanarious",
    "contributions": 1
  },
  {
    "name": "candrapersada",
    "link": "https://github.com/candrapersada",
    "contributions": 1
  },
  {
    "name": "harleylara",
    "link": "https://github.com/harleylara",
    "contributions": 1
  },
  {
    "name": "sitiom",
    "link": "https://github.com/sitiom",
    "contributions": 1
  },
  {
    "name": "victorelec14",
    "link": "https://github.com/victorelec14",
    "contributions": 1
  }
]