# Autogenerated file, do not modify it!!!

contributors = [
  "marticliment",
  "ppvnf",
  "panther7",
  "RavenMacDaddy",
  "adripo",
  "MisterEvans78",
  "sklart",
  "vedantmgoyal2009",
  "candrapersada",
  "elliot-100",
  "neoOpus",
  "rumplin",
  "Satanarious",
  "quantumfallout",
  "flatron4eg",
  "harleylara",
  "sitiom",
  "victorelec14"
]

contributorsInfo = [
  {
    "name": "marticliment",
    "link": "https://github.com/marticliment",
    "contributions": 1252
  },
  {
    "name": "ppvnf",
    "link": "https://github.com/ppvnf",
    "contributions": 88
  },
  {
    "name": "panther7",
    "link": "https://github.com/panther7",
    "contributions": 58
  },
  {
    "name": "RavenMacDaddy",
    "link": "https://github.com/RavenMacDaddy",
    "contributions": 21
  },
  {
    "name": "adripo",
    "link": "https://github.com/adripo",
    "contributions": 6
  },
  {
    "name": "MisterEvans78",
    "link": "https://github.com/MisterEvans78",
    "contributions": 4
  },
  {
    "name": "sklart",
    "link": "https://github.com/sklart",
    "contributions": 3
  },
  {
    "name": "vedantmgoyal2009",
    "link": "https://github.com/vedantmgoyal2009",
    "contributions": 2
  },
  {
    "name": "candrapersada",
    "link": "https://github.com/candrapersada",
    "contributions": 2
  },
  {
    "name": "elliot-100",
    "link": "https://github.com/elliot-100",
    "contributions": 2
  },
  {
    "name": "neoOpus",
    "link": "https://github.com/neoOpus",
    "contributions": 1
  },
  {
    "name": "rumplin",
    "link": "https://github.com/rumplin",
    "contributions": 1
  },
  {
    "name": "Satanarious",
    "link": "https://github.com/Satanarious",
    "contributions": 1
  },
  {
    "name": "quantumfallout",
    "link": "https://github.com/quantumfallout",
    "contributions": 1
  },
  {
    "name": "flatron4eg",
    "link": "https://github.com/flatron4eg",
    "contributions": 1
  },
  {
    "name": "harleylara",
    "link": "https://github.com/harleylara",
    "contributions": 1
  },
  {
    "name": "sitiom",
    "link": "https://github.com/sitiom",
    "contributions": 1
  },
  {
    "name": "victorelec14",
    "link": "https://github.com/victorelec14",
    "contributions": 1
  }
]