# Autogenerated file, do not modify it!!!

contributors = [
  "marticliment",
  "ppvnf",
  "panther7",
  "RavenMacDaddy",
  "Mikey1993",
  "adripo",
  "MisterEvans78",
  "rumplin",
  "uKER",
  "sklart",
  "aaronliu0130",
  "vedantmgoyal2009",
  "adfnekc",
  "BastianKamp",
  "candrapersada",
  "elliot-100",
  "raghavdhingra24",
  "sitiom",
  "joguarino",
  "neoOpus",
  "Carterpersall",
  "HorridModz",
  "reima",
  "Satanarious"
]

contributorsInfo = [
  {
    "name": "marticliment",
    "link": "https://github.com/marticliment",
    "contributions": 2105
  },
  {
    "name": "ppvnf",
    "link": "https://github.com/ppvnf",
    "contributions": 95
  },
  {
    "name": "panther7",
    "link": "https://github.com/panther7",
    "contributions": 71
  },
  {
    "name": "RavenMacDaddy",
    "link": "https://github.com/RavenMacDaddy",
    "contributions": 21
  },
  {
    "name": "Mikey1993",
    "link": "https://github.com/Mikey1993",
    "contributions": 15
  },
  {
    "name": "adripo",
    "link": "https://github.com/adripo",
    "contributions": 6
  },
  {
    "name": "MisterEvans78",
    "link": "https://github.com/MisterEvans78",
    "contributions": 4
  },
  {
    "name": "rumplin",
    "link": "https://github.com/rumplin",
    "contributions": 3
  },
  {
    "name": "uKER",
    "link": "https://github.com/uKER",
    "contributions": 3
  },
  {
    "name": "sklart",
    "link": "https://github.com/sklart",
    "contributions": 3
  },
  {
    "name": "aaronliu0130",
    "link": "https://github.com/aaronliu0130",
    "contributions": 2
  },
  {
    "name": "vedantmgoyal2009",
    "link": "https://github.com/vedantmgoyal2009",
    "contributions": 2
  },
  {
    "name": "adfnekc",
    "link": "https://github.com/adfnekc",
    "contributions": 2
  },
  {
    "name": "BastianKamp",
    "link": "https://github.com/BastianKamp",
    "contributions": 2
  },
  {
    "name": "candrapersada",
    "link": "https://github.com/candrapersada",
    "contributions": 2
  },
  {
    "name": "elliot-100",
    "link": "https://github.com/elliot-100",
    "contributions": 2
  },
  {
    "name": "raghavdhingra24",
    "link": "https://github.com/raghavdhingra24",
    "contributions": 2
  },
  {
    "name": "sitiom",
    "link": "https://github.com/sitiom",
    "contributions": 2
  },
  {
    "name": "joguarino",
    "link": "https://github.com/joguarino",
    "contributions": 2
  },
  {
    "name": "neoOpus",
    "link": "https://github.com/neoOpus",
    "contributions": 1
  },
  {
    "name": "Carterpersall",
    "link": "https://github.com/Carterpersall",
    "contributions": 1
  },
  {
    "name": "HorridModz",
    "link": "https://github.com/HorridModz",
    "contributions": 1
  },
  {
    "name": "reima",
    "link": "https://github.com/reima",
    "contributions": 1
  },
  {
    "name": "Satanarious",
    "link": "https://github.com/Satanarious",
    "contributions": 1
  }
]