# Autogenerated file, do not modify it!!!

untranslatedPercentage = {
  "bn": "19%",
  "da": "0%",
  "de": "92%",
  "es": "66%",
  "hi": "85%",
  "hr": "0%",
  "hu": "99%",
  "id": "9%",
  "it": "99%",
  "ja": "93%",
  "ko": "63%",
  "pl": "38%",
  "ru": "85%",
  "sr": "22%",
  "tr": "89%",
  "ua": "85%",
  "zh_TW": "89%"
}

languageCredits = {
  "ar": [
    {
      "name": "Abdullah AS",
      "link": ""
    },
    {
      "name": "MahmoudAdel",
      "link": ""
    }
  ],
  "bg": [
    {
      "name": "Vasil Kolev",
      "link": ""
    }
  ],
  "bn": [
    {
      "name": "Nilavra Bhattacharya",
      "link": ""
    }
  ],
  "ca": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "cs": [
    {
      "name": "panther7",
      "link": "https://github.com/panther7"
    },
    {
      "name": "Petr Janeček",
      "link": ""
    }
  ],
  "da": [],
  "de": [
    {
      "name": "Datacra5H",
      "link": ""
    }
  ],
  "en": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    },
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "es": [
    {
      "name": "rubnium",
      "link": "https://github.com/rubnium"
    }
  ],
  "fr": [
    {
      "name": "Evans Costa",
      "link": ""
    }
  ],
  "hi": [
    {
      "name": "Satyam Singh Niranjan",
      "link": ""
    }
  ],
  "hr": [
    {
      "name": "Nemanja Djurcic",
      "link": ""
    }
  ],
  "hu": [
    {
      "name": "gidano",
      "link": ""
    }
  ],
  "id": [
    {
      "name": "arthackrc",
      "link": "https://github.com/arthackrc"
    }
  ],
  "it": [
    {
      "name": "GiacoBot",
      "link": ""
    },
    {
      "name": "Maicol Battistini",
      "link": ""
    },
    {
      "name": "Rosario Di Mauro",
      "link": ""
    }
  ],
  "ja": [
    {
      "name": "sho9029",
      "link": ""
    },
    {
      "name": "Yuki Takase",
      "link": ""
    }
  ],
  "ko": [
    {
      "name": "shblue21",
      "link": "https://github.com/shblue21"
    }
  ],
  "nl": [
    {
      "name": "abbydiode",
      "link": "https://github.com/abbydiode"
    },
    {
      "name": "Stephan Paternotte",
      "link": ""
    }
  ],
  "pl": [
    {
      "name": "regulargvy13",
      "link": ""
    }
  ],
  "pt_BR": [
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "pt_PT": [
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "ru": [
    {
      "name": "Sergey",
      "link": ""
    },
    {
      "name": "Артем",
      "link": ""
    }
  ],
  "sr": [
    {
      "name": "Nemanja Djurcic",
      "link": ""
    }
  ],
  "tr": [
    {
      "name": "Ahmet Özmetin",
      "link": ""
    }
  ],
  "ua": [
    {
      "name": "Artem Moldovanenko",
      "link": ""
    },
    {
      "name": "Operator404",
      "link": ""
    }
  ],
  "zh_CN": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "BUGP Association",
      "link": ""
    },
    {
      "name": "ciaran",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    }
  ],
  "zh_TW": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    },
    {
      "name": "yrctw",
      "link": ""
    }
  ]
}