# Autogenerated file, do not modify it!!!

untranslatedPercentage = {
  "ar": "97%",
  "bg": "97%",
  "bn": "18%",
  "da": "52%",
  "de": "97%",
  "es": "97%",
  "fr": "97%",
  "hi": "82%",
  "hr": "0%",
  "hu": "97%",
  "id": "17%",
  "it": "96%",
  "ja": "91%",
  "ko": "97%",
  "nl": "97%",
  "pl": "97%",
  "pt_BR": "97%",
  "pt_PT": "97%",
  "ru": "82%",
  "sr": "21%",
  "tr": "86%",
  "ua": "86%",
  "zh_CN": "97%",
  "zh_TW": "86%"
}

languageCredits = {
  "ar": [
    {
      "name": "Abdu11ahAS",
      "link": "https://github.com/Abdu11ahAS"
    },
    {
      "name": "Abdullah A.S",
      "link": ""
    }
  ],
  "bg": [
    {
      "name": "Vasil Kolev",
      "link": ""
    }
  ],
  "bn": [
    {
      "name": "Nilavra Bhattacharya",
      "link": ""
    }
  ],
  "ca": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "cs": [
    {
      "name": "panther7",
      "link": "https://github.com/panther7"
    },
    {
      "name": "Petr Janeček",
      "link": ""
    }
  ],
  "da": [
    {
      "name": "mikkolukas",
      "link": "https://github.com/mikkolukas"
    }
  ],
  "de": [
    {
      "name": "Datacra5H",
      "link": ""
    }
  ],
  "en": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    },
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "es": [
    {
      "name": "dalbitresb12",
      "link": "https://github.com/dalbitresb12"
    },
    {
      "name": "JMoreno97",
      "link": "https://github.com/JMoreno97"
    },
    {
      "name": "rubnium",
      "link": "https://github.com/rubnium"
    }
  ],
  "fr": [
    {
      "name": "Evans Costa",
      "link": ""
    }
  ],
  "hi": [
    {
      "name": "Satyam Singh Niranjan",
      "link": ""
    }
  ],
  "hr": [
    {
      "name": "Nemanja Djurcic",
      "link": ""
    }
  ],
  "hu": [
    {
      "name": "gidano",
      "link": ""
    }
  ],
  "id": [
    {
      "name": "arthackrc",
      "link": "https://github.com/arthackrc"
    }
  ],
  "it": [
    {
      "name": "GiacoBot",
      "link": ""
    },
    {
      "name": "Maicol Battistini",
      "link": ""
    },
    {
      "name": "Rosario Di Mauro",
      "link": ""
    }
  ],
  "ja": [
    {
      "name": "sho9029",
      "link": ""
    },
    {
      "name": "Yuki Takase",
      "link": ""
    }
  ],
  "ko": [
    {
      "name": "shblue21",
      "link": "https://github.com/shblue21"
    }
  ],
  "nl": [
    {
      "name": "abbydiode",
      "link": "https://github.com/abbydiode"
    },
    {
      "name": "Stephan-P",
      "link": "https://github.com/Stephan-P"
    }
  ],
  "pl": [
    {
      "name": "KamilZielinski",
      "link": "https://github.com/KamilZielinski"
    },
    {
      "name": "RegularGvy13",
      "link": ""
    }
  ],
  "pt_BR": [
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "pt_PT": [
    {
      "name": "ppvnf",
      "link": "https://github.com/ppvnf"
    }
  ],
  "ru": [
    {
      "name": "Sergey",
      "link": ""
    },
    {
      "name": "Артем",
      "link": ""
    }
  ],
  "sr": [
    {
      "name": "Nemanja Djurcic",
      "link": ""
    }
  ],
  "tr": [
    {
      "name": "Ahmet Özmetin",
      "link": ""
    }
  ],
  "ua": [
    {
      "name": "Artem Moldovanenko",
      "link": ""
    },
    {
      "name": "Operator404",
      "link": ""
    }
  ],
  "zh_CN": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "BUGP Association",
      "link": ""
    },
    {
      "name": "ciaran",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    }
  ],
  "zh_TW": [
    {
      "name": "Aaron Liu",
      "link": ""
    },
    {
      "name": "Cololi",
      "link": ""
    },
    {
      "name": "yrctw",
      "link": ""
    }
  ]
}