[CmdletBinding(DefaultParameterSetName = 'Selected')]
param(
    [Parameter(ParameterSetName = 'Selected', Mandatory = $true)]
    [string[]]$LanguageCodes,

    [Parameter(ParameterSetName = 'All')]
    [switch]$AllLanguages,

    [switch]$UpdateReadme,

    [string]$ReadmePath = (Join-Path $PSScriptRoot '..\README.md'),

    [string]$TranslatedPercentagesPath = (Join-Path $PSScriptRoot '..\src\UniGetUI.Core.LanguageEngine\Assets\Data\TranslatedPercentages.json')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'Languages\LangData.psm1') -Force

function Read-JsonObject {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -Path $Path -PathType Leaf)) {
        return [ordered]@{}
    }

    $content = [System.IO.File]::ReadAllText($Path)
    if ([string]::IsNullOrWhiteSpace($content)) {
        return [ordered]@{}
    }

    $parsed = $content | ConvertFrom-Json -AsHashtable
    if ($null -eq $parsed) {
        return [ordered]@{}
    }

    if (-not ($parsed -is [System.Collections.IDictionary])) {
        throw "JSON root must be an object: $Path"
    }

    return $parsed
}

function Write-Utf8File {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Content
    )

    $encoding = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Get-NewLine {
    param(
        [AllowEmptyString()]
        [string]$Content
    )

    if ($Content -match "`r`n") {
        return "`r`n"
    }

    return "`n"
}

$statusJson = & (Join-Path $PSScriptRoot 'get_translation_status.ps1') -OutputFormat Json
$statusRows = $statusJson | ConvertFrom-Json -AsHashtable
if ($null -eq $statusRows) {
    throw 'Could not load translation status data.'
}

$statusByCode = @{}
foreach ($row in $statusRows) {
    $statusByCode[[string]$row.Code] = $row
}

$codesToUpdate = @()
if ($AllLanguages.IsPresent) {
    $codesToUpdate = @($statusByCode.Keys | Sort-Object)
}
else {
    $codesToUpdate = @($LanguageCodes | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Sort-Object -Unique)
}

if ($codesToUpdate.Count -eq 0) {
    throw 'No language codes were provided.'
}

$storedPercentages = Read-JsonObject -Path $TranslatedPercentagesPath
$updatedPercentages = [ordered]@{}
foreach ($entry in $storedPercentages.GetEnumerator()) {
    $updatedPercentages[[string]$entry.Key] = [string]$entry.Value
}

foreach ($code in $codesToUpdate) {
    if (-not $statusByCode.ContainsKey($code)) {
        throw "Language code '$code' was not found in the computed translation status."
    }

    $updatedPercentages[$code] = [string]$statusByCode[$code].Completion
}

$percentagesJson = ($updatedPercentages | ConvertTo-Json -Depth 5)
Write-Utf8File -Path $TranslatedPercentagesPath -Content $percentagesJson

if ($UpdateReadme.IsPresent) {
    $readmeContent = [System.IO.File]::ReadAllText($ReadmePath)
    $newLine = Get-NewLine -Content $readmeContent
    $generatedTable = Get-MarkdownSupportLangs
    $generatedTable = $generatedTable -replace "`r?`n", $newLine
    $replacementBlock = @(
        '<!-- Autogenerated translations -->',
        $generatedTable.TrimEnd(),
        '',
        ('Last updated: ' + (Get-Date).ToString('ddd MMM dd HH:mm:ss yyyy')),
        '<!-- END Autogenerated translations -->'
    ) -join $newLine

    $pattern = '<!-- Autogenerated translations -->[\s\S]*?<!-- END Autogenerated translations -->'
    if ($readmeContent -notmatch $pattern) {
        throw 'Could not locate the autogenerated translations block in README.md.'
    }

    $updatedReadmeContent = [System.Text.RegularExpressions.Regex]::Replace(
        $readmeContent,
        $pattern,
        [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $replacementBlock },
        [System.Text.RegularExpressions.RegexOptions]::None,
        [TimeSpan]::FromSeconds(2)
    )

    Write-Utf8File -Path $ReadmePath -Content $updatedReadmeContent
}

Write-Output ('Updated translation status metadata for: ' + ($codesToUpdate -join ', '))