name: .NET Tests
on:
  push:
    branches: [ "main" ]
    paths:
      - 'global.json'
      - '**.cs'
      - '**.csproj'
      - '**.props'
      - '**.targets'
      - '**.sln'
      - 'src/.editorconfig'
      - '.github/workflows/dotnet-test.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'global.json'
      - '**.cs'
      - '**.csproj'
      - '**.props'
      - '**.targets'
      - '**.sln'
      - 'src/.editorconfig'
      - '.github/workflows/dotnet-test.yml'

  workflow_dispatch:

jobs:
  test-codebase:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Cache NuGet packages
      uses: actions/cache@v5
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('global.json', 'src/**/*.csproj', 'src/**/*.props', 'src/**/*.targets', 'src/**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      working-directory: src
      run: dotnet restore UniGetUI.sln

    - name: Check whitespace formatting
      run: dotnet format whitespace src --folder --verify-no-changes --verbosity minimal

    - name: Check code style formatting
      working-directory: src
      run: dotnet format style UniGetUI.sln --no-restore --verify-no-changes --verbosity minimal

    - name: Run Tests
      working-directory: src
      run: dotnet test UniGetUI.sln --no-restore --verbosity q --nologo

