name: Retrieve latest icons from excel file

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  load-icons:
    if: github.repository == 'marticliment/UniGetUI'
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download icons json file
        run: |
          python -m pip install xlrd==1.2.0
          git config user.email "excelbot@github.com"
          git config user.name "Excel Bot"
          python scripts/generate_json_from_excel.py 
          git commit WebBasedData/screenshot-database.json -m "Update icons and screenshots"
          exit 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          base: main
          title: "Update icons and screenshots from the excel file"
          reviewers: "${{ github.repository_owner }}"
          author: "Excel Bot <excel-bot@users.noreply.github.com>"
          commit-message: "Update icons and screenshots from the excel file"
          branch: pull-request/update-icons-and-screenshots
